// Code generated by gluon; DO NOT EDIT.
package main

import (
	embed "embed"
	fiber "github.com/go-gluon/fiber"
	gluon "github.com/go-gluon/gluon"
	zerolog "github.com/go-gluon/zerolog"
)

//go:embed resources/*
var resources embed.FS

// Create gluon instance
var g = gluon.CreateGluon("example", "0.0.0", "v0.0.0", &resources,
	gluon.NewExtension("zerolog", 10, "v0.0.0", false, &zerolog.ZerologExtension{}),
	gluon.NewExtension("fiber", 100, "v0.0.0", true, &fiber.FiberService{}),
)

// Main method
func main() {
	g.Start()
}
